image: node:16.8.0

pipelines:
  branches:
    staging:
      - step:
          name: Build
          script:
            - yarn install
            - REACT_APP_BUGSNAG_API_KEY=$BUGSNAG_API_KEY
            - REACT_APP_LIFF_ID=$LIFF_ID_STAGING
            - yarn build:staging
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "staging"
                DEBUG: "true"
    master:
      - step:
          name: Build
          script:
            - yarn install && yarn build LIFF_ID=$LIFF_ID_PRODUCTION
            - REACT_APP_BUGSNAG_API_KEY=$BUGSNAG_API_KEY
            - REACT_APP_GA_TRACKING_ID=$GA_TRACKING_ID
            - REACT_APP_LIFF_ID=$LIFF_ID_PRODUCTION
            - yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "production"
                DEBUG: "true"
