image: node:16.8.0

pipelines:
  branches:
    staging:
      - step:
          name: Build
          script:
            - yarn install && yarn build:staging LIFF_ID=$LIFF_ID_STAGING
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: staging
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "staging"
                DEBUG: "true"
    master:
      - step:
          name: Build
          script:
            - yarn install && yarn build LIFF_ID=$LIFF_ID_PRODUCTION
          artifacts:
            - build/**
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: "production"
                DEBUG: "true"
